### ISSUE TITLE
[Feature]: Additional information about object(s) available to map in file kind integration

### ISSUE THREAD

**Issue by reinrl** [port-labs/port-docs#2274]
### 🚀 Feature Proposal

I specifically had questions when working on an [Azure DevOps file kind integration](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples/#mapping-files), but I would imagine that other similar Git integrations could use similar explanation.

It would be nice to know more about the specific objects/keys that are available when creating the mapping for a file kind. As an example, I believe that the file object itself a file size, both raw and parsed content, and some other metadata (?) - and that the repo object includes the repo name and a child project object (which itself includes a name)...but this mostly from a bit of looking at [code](https://github.com/port-labs/ocean/blob/main/integrations/azure-devops/azure_devops/client/file_processing.py) and some trial and error. What else is available?

### Motivation and example

See above - would be nice to know exactly what is available to me as I attempt to map in a file from Azure DevOps - perhaps as a part of [this tip section](https://github.com/port-labs/port-docs/blob/b53fb10c0d215dbdaf81c38634edfe904d4ad5ea/docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-file/_azuredevops_exporter_example_file_port_app_config.mdx?plain=1#L5)?

**Comment by reinrl** [comment]
The [example configuration](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples/#configuration) also doesn't appear to work as is - if you look at [the code](https://github.com/port-labs/ocean/blob/main/integrations/azure-devops/azure_devops/client/file_processing.py#L99), `.file.content` is an object - but the sample mapping in the configuration section attempts to map that object directly into a string property.

**Comment by PeyGis** [comment]
Hi @reinrl,

Thank you for sharing your feedback on our Azure DevOps (ADO) file kind implementation — we appreciate it. Below are responses to the issues you raised:


### 1. `.file.content` Mapping Error

You're absolutely right — the current mapping in the documentation referencing `.file.content` is incorrect. The `file.content` field is an **object** containing two keys: `raw` and `parsed`. Since the mapping expects a string, the correct value should be `.file.content.raw`.

✅ We'll update both the documentation and the integration configuration to reflect this and prevent further issues.


### 2. Viewing All Available `file` Kind Properties

To view the full list of metadata and properties available for the `file` kind:

1. Go to your [Data Sources](https://app.getport.io/settings/data-sources) page.
2. Select the **Azure DevOps** integration.
3. Under the **Mapping Editor** tab, scroll to the `file` kind.
4. You’ll see a complete list of available fields there, like in the screenshot below:  
   ![Image](https://github.com/user-attachments/assets/211d68b3-7b29-4d20-9a74-debd1608fef4)


### 3. Pro Tip: Use Dedicated Property Types for File Content

To enhance how file content is visualized in your catalog, we recommend creating blueprint properties tailored to the file format.

If you're working with YAML or JSON files, here's a practical approach:

#### 🔧 Step 1: Add properties to your `file` blueprint

```json
"file_content_yaml": {
  "icon": "DefaultProperty",
  "type": "string",
  "title": "File Content YAML",
  "format": "yaml"
},
"file_content_json": {
  "type": "object",
  "title": "File Content JSON"
}
```

#### Step 2: Update your mapping under the `file` kind

```yaml
- kind: file
  selector:
    query: 'true'
    files:
      path:
        - pipeline.yaml
  port:
    entity:
      mappings:
        identifier: .repo.name + "/" + .file.objectId
        title: .file.path
        blueprint: '"file"'
        properties:
          path: .file.path
          size: .file.size
          content: .file.content.raw
          file_content_yaml: .file.content.raw
          file_content_json: .file.content.parsed
          link: .repo.remoteUrl + "?path=" + (.file.path)
        relations:
          repository: >-
            "\(.repo.project.name | ascii_downcase | gsub("[ ();]"; ""))/\(.repo.name | ascii_downcase | gsub("[ ();]"; ""))"
```
**Note**: `.file.content.parsed` is always a JSON object, which is why we map it to the `file_content_json` property.

### Taking It Further: Extracting Fields from JSON Files

Since `.file.content.parsed` is a structured JSON object, you can extract specific fields directly into blueprint properties.

For example, if you're syncing a `package.json` file, here’s how you can extract version and dependencies:

```yaml
- kind: file
  selector:
    query: 'true'
    files:
      path:
        - package.json
  port:
    entity:
      mappings:
        identifier: .repo.name + "/" + .file.objectId
        title: .file.path
        blueprint: '"file"'
        properties:
          path: .file.path
          size: .file.size
          content: .file.content.raw
          project_version: .file.content.parsed.version
          project_dependencies: .file.content.parsed.dependencies
          link: .repo.remoteUrl + "?path=" + (.file.path)
        relations:
          repository: >-
            "\(.repo.project.name | ascii_downcase | gsub("[ ();]"; ""))/\(.repo.name | ascii_downcase | gsub("[ ();]"; ""))"
```

### Bonus: Create Multiple Entities from One File

If your file contains an array of items and you'd like to create one entity per item (e.g., a list of configs in a YAML or JSON file), check out our `itemsToParse` functionality in this [GitHub file mapping example](https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples#map-files-and-file-contents).


Let us know if you have further questions or ideas!
